services:
  - type: web
    name: browser
    env: node
    plan: free
    buildCommand: "yarn install"
    startCommand: "node backend/server.js"
    envVars:
      - key: NODE_VERSION
        value: 22.16.0
